# Generated by Django 5.2 on 2025-04-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junk_app', '0002_create_user_profiles'),
        ('junk_app', '0002_userprofile'),
    ]

    operations = [
    ]
